#!/bin/bash
#
## makepl
## Copyright 2001 Lars Engebretsen
#
# This work may be distributed and/or modified under the
# conditions of the LaTeX Project Public License, either version 1.3
# of this license or (at your option) any later version.
# The latest version of this license is in
#   http://www.latex-project.org/lppl.txt
# and version 1.3 or later is part of all distributions of LaTeX
# version 2005/12/01 or later.
#
# This work has the LPPL maintenance status `maintained'.
# 
# The Current Maintainer of this work is Lars Engebretsen.
#
# This work consists of all files listed in MANIFEST.
#
rm cm*.mtx cm*.pl
for file in cmb10 cmbsy10 cmbx{5,6,7,8,9,10,12} cmbxsl10 cmcsc10 cmex10 \
      cmff10 cmfi10 cmfib8 cmitt10 cmmi{5,6,7,8,9,10,12,b10} \
      cmr{5,6,7,8,9,10,12,17} cmsl{8,9,10,12,tt10} \
      cmss{8,9,10,12,17,bx10,dc10,q8} cmssi{8,9,10,12,17} \
      cmsy{5,6,7,8,9,10} cmtcsc10 \
      cmtex{8,9} cmtt{8,9,10,12} cmvtt10 \
      lcmss{,b,i}8; do
    tftopl $file.tfm > $file.pl
done
for file in cmti{7,8,9,10,12} cmu10 cmbxti10; do
    tftopl $file.tfm | sed 's/TEX TEXT/TEX TEXT ITALIC/' > $file.pl
done
