# SPDX-FileCopyrightText: 2025 2023 XWiki CryptPad Team <contact@cryptpad.org> and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Trigger E2E tests

on:
  push:
    branches: [ staging ]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger E2E test run - local and remote
        run: |
          repo_owner="cryptpad" 
          repo_name="e2e-test-suite"  
          event_type="trigger-e2e-tests" 
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TEST_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cryptpad/e2e-test-suite/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
